python dgt/run.py \
 --multirun \
 wandb_conf.name=EGCNH_Search_TwitterRG \
 dataset=REG-TwitterTennisRG17 \
 model=EvolveGCNH \
 task=node_reg \
 task_name=node_reg \
 gpu=1 \
 lr=0.1,0.01,0.001 \
 task.engine.batch_size=128 \
 model.evolving=False \
 model.clip_grad=True \
 model.pred_next=False \
 model.one_hot=False \
 model.node_reg.in_channels=32 \
 model.node_reg.num_layers_rnn=1,2 \
 model.node_reg.improved=True \
 model.node_reg.cached=False \
 model.node_reg.add_self_loops=False \
 model.node_reg.use_edge_weight=False \
 model.node_reg.undirected=True \
 model.node_reg.task_name=node_reg \
 optim.optimizer.weight_decay=0.001 \
 task.engine.n_runs=1 \
 task.engine.epoch=100 \