python dgt/run.py \
 --multirun \
 wandb_conf.name=GCLSTM_Search_TwitterRG \
 dataset=REG-TwitterTennisRG17 \
 model=GCLSTM \
 task=node_reg \
 task_name=node_reg \
 gpu=0 \
 lr=0.1,0.01,0.001,0.0001  \
 task.engine.batch_size=128 \
 model.evolving=False \
 model.one_hot=False \
 model.clip_grad=True \
 model.pred_next=False \
 model.node_reg.in_channels=64 \
 model.node_reg.K=2 \
 model.node_reg.normalization=sym \
 model.node_reg.bias=False \
 model.node_reg.undirected=True \
 model.node_reg.task_name=node_reg \
 optim.optimizer.weight_decay=0 \
 task.engine.n_runs=1 \
 task.engine.epoch=50 \