python dgt/run.py \
 --multirun \
 dataset=DGB-UCI-Message \
 wandb_conf.name=EGCNH_Search_Rnd_Message \
 gpu=2 \
 lr=0.001,0.01,0.1 \
 model=EvolveGCNH \
 model.evolving=False \
 model.pred_next=False \
 model.clip_grad=True,False \
 model.link_pred.num_layers_rnn=1,2 \
 model.link_pred.improved=False,True \
 model.link_pred.cached=True,False \
 model.link_pred.add_self_loops=True,False \
 model.link_pred.use_edge_weight=False \
 model.link_pred.undirected=True \
 task.engine.n_runs=1 \
 task.engine.epoch=20 \
 task.engine.batch_size=1024 \
 optim.optimizer.weight_decay=0,0.0001 \
