python dgt/run.py \
 --multirun \
 wandb_conf.name=GIN_Search_TwitterRG \
 dataset=REG-TwitterTennisRG17 \
 model=Static \
 model.name=GIN \
 task=node_reg \
 task_name=node_reg \
 gpu=1 \
 lr=0.1,0.01,0.001,0.0001,0.0005 \
 model.evolving=True \
 model.clip_grad=True \
 model.one_hot=False \
 model.node_reg.layers=1 \
 model.node_reg.task_name=node_reg \
 optim.optimizer.weight_decay=0 \
 task.engine.n_runs=1 \
 task.engine.epoch=200 \
 task.engine.batch_size=128 \